name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 bandit

    - name: Run Flake8
      run: |
        flake8 ./app --count --exit-zero --max-complexity=10 --statistics

    - name: Run Bandit
      run: |
        bandit -r ./app -lll -iii

    - name: Run pytest
      run: |
        pytest tests

    - name: Run pytest-cov
      run: |
        pytest --cov-fail-under=90 --cov=./app ./tests/